### ISSUE TITLE
10 test failures locally

### ISSUE THREAD

**Issue by tylerl0706** [promptworks/elastic_sync#8]
I was trying to run the tests after I forked and I'm receiving several failures:

```
 1) test delete/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:69
     match (=) failed
     code: {:ok, 200, _} = Repo.delete(%Thing{id: 1, name: "pasta"})
     rhs:  :error
     stacktrace:
       test/elastic_sync/repo_test.exs:71: (test)

.........

  2) test insert/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:45
     ** (MatchError) no match of right hand side value: {:ok, 200, %{_id: "1", _index: "elastic_sync_test", _shards: %{failed: 0, successful: 1, total: 2}, _type: "things", _version: 10, created: false, result: "updated"}}
     stacktrace:
       test/elastic_sync/repo_test.exs:46: (test)

.

  3) test delete!/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:75
     ** (FunctionClauseError) no function clause matching in Tirexs.HTTP.ok!/1
     stacktrace:
       (tirexs) lib/tirexs/http.ex:320: Tirexs.HTTP.ok!(:error)
       test/elastic_sync/repo_test.exs:77: (test)



  4) test reindexes the index (Mix.Tasks.ElasticSync.ReindexTest)
     test/mix/tasks/elastic_sync/reindex_test.exs:13
     ** (CaseClauseError) no case clause matching: {:error, 400, %{error: %{index: "elastic_sync_test", index_uuid: "GXw3p_azQWSWliqzKB1QyA", reason: "Invalid alias name [elastic_sync_test], an index exists with the same name as the alias", root_cause: [%{index: "elastic_sync_test", index_uuid: "GXw3p_azQWSWliqzKB1QyA", reason: "Invalid alias name [elastic_sync_test], an index exists with the same name as the alias", type: "invalid_alias_name_exception"}], type: "invalid_alias_name_exception"}, status: 400}}
     stacktrace:
       (elastic_sync) lib/mix/tasks/elastic_sync/reindex.ex:9: Mix.Tasks.ElasticSync.Reindex.run/1
       test/mix/tasks/elastic_sync/reindex_test.exs:18: (test)

..........

  5) test delete with a changeset (ElasticSync.SyncRepoTest)
     test/elastic_sync/sync_repo_test.exs:44
     match (=) failed
     code: {:ok, _} = TestSyncRepo.delete(Thing.changeset(thing))
     rhs:  :error
     stacktrace:
       test/elastic_sync/sync_repo_test.exs:46: (test)



  6) test delete (ElasticSync.SyncRepoTest)
     test/elastic_sync/sync_repo_test.exs:39
     match (=) failed
     code: {:ok, _} = TestSyncRepo.delete(thing)
     rhs:  :error
     stacktrace:
       test/elastic_sync/sync_repo_test.exs:41: (test)

...

  7) test get_alias/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:14
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



  8) test remove_indicies/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:33
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



  9) test replace_alias/2 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:27
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



 10) test create/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:21
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



Finished in 1.4 seconds
34 tests, 10 failures
```

I noticed in `iex` that if I alias `Tirexs.HTTP` and try to delete something ( `HTTP.delete("/*")` ) The call just returns `:error` with no other information.

Have you received this before?

I tried with Elixir 1.4.2, 1.4.1 & 1.3.0

since Tirexs 0.8 wants elixir 1.3.0.

Side note: I noticed this: `the dependency :postgrex requires Elixir "~> 1.3.4 or ~> 1.4" but you are running on v1.3.0` which might be an issue because of the Tirexs dependency that wants 1.3.0. (looks like Tirexs is [working on upgrading though]!(https://github.com/Zatvobor/tirexs/commit/b419723de4eaa2798c8732707bd7177c87b212a9)

**Comment by rzane** [comment]
No. Are you sure elasticsearch is running and accessible at localhost:9200?

Also, I'm using elasticsearch 2.3.3, which probably isn't the issue, but it could be related.

**Comment by tylerl0706** [comment]
I'm positive. In fact, I ran `HTTP.url("/*")` and copy pasted that right
into Postman and set the method to DELETE and it worked.

I mentioned earlier that elasticsearch was running on a different port...
I've since changed that to the normal 9200 for consistency.

I AM using Elastic Search 5.3... I'm hoping that's not the issue :/

I don't think it should be. There weren't too many breaking changes from
2.x to 5.x AFAIK.

Maybe I need to be taking this up with the Tirexs folks?

I'm definitely in the wrong somewhere... Just not sure where.

**Comment by rzane** [comment]
Yeah, not sure what the problem is, but it sounds like it's related to your system configuration in some way. I just setup docker-compose, so maybe try that.

**Comment by tylerl0706** [comment]
The test failures continue... It has to be something so small that we're missing.

```
Creating elasticsync_elasticsearch_1
Creating elasticsync_postgres_1


  1) test reindexes the index (Mix.Tasks.ElasticSync.ReindexTest)
     test/mix/tasks/elastic_sync/reindex_test.exs:13
     ** (CaseClauseError) no case clause matching: {:error, 400, %{error: %{index: "elastic_sync_test", index_uuid: "WyvvBqZwR4mmH4Wsvbgfbg", reason: "Invalid alias name [elastic_sync_test], an index exists with the same name as the alias", root_cause: [%{index: "elastic_sync_test", index_uuid: "WyvvBqZwR4mmH4Wsvbgfbg", reason: "Invalid alias name [elastic_sync_test], an index exists with the same name as the alias", type: "invalid_alias_name_exception"}], type: "invalid_alias_name_exception"}, status: 400}}
     stacktrace:
       (elastic_sync) lib/mix/tasks/elastic_sync/reindex.ex:9: Mix.Tasks.ElasticSync.Reindex.run/1
       test/mix/tasks/elastic_sync/reindex_test.exs:18: (test)

.

  2) test delete with a changeset (ElasticSync.SyncRepoTest)
     test/elastic_sync/sync_repo_test.exs:44
     ** (FunctionClauseError) no function clause matching in Tirexs.HTTP.ok!/1
     stacktrace:
       (tirexs) lib/tirexs/http.ex:320: Tirexs.HTTP.ok!(:error)
       (elastic_sync) lib/elastic_sync/sync_repo.ex:99: ElasticSync.SyncRepo.sync_one/3
       test/elastic_sync/sync_repo_test.exs:46: (test)



  3) test delete (ElasticSync.SyncRepoTest)
     test/elastic_sync/sync_repo_test.exs:39
     ** (FunctionClauseError) no function clause matching in Tirexs.HTTP.ok!/1
     stacktrace:
       (tirexs) lib/tirexs/http.ex:320: Tirexs.HTTP.ok!(:error)
       (elastic_sync) lib/elastic_sync/sync_repo.ex:99: ElasticSync.SyncRepo.sync_one/3
       test/elastic_sync/sync_repo_test.exs:41: (test)

.......

  4) test delete!/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:74
     ** (FunctionClauseError) no function clause matching in Tirexs.HTTP.ok!/1
     stacktrace:
       (tirexs) lib/tirexs/http.ex:320: Tirexs.HTTP.ok!(:error)
       test/elastic_sync/repo_test.exs:76: (test)

...........

  5) test insert/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:44
     ** (MatchError) no match of right hand side value: {:ok, 200, %{_id: "1", _index: "elastic_sync_test", _shards: %{failed: 0, successful: 1, total: 2}, _type: "things", _version: 23, created: false, result: "updated"}}
     stacktrace:
       test/elastic_sync/repo_test.exs:45: (test)



  6) test delete/1 (ElasticSync.RepoTest)
     test/elastic_sync/repo_test.exs:68
     ** (FunctionClauseError) no function clause matching in Tirexs.HTTP.ok!/1
     stacktrace:
       (tirexs) lib/tirexs/http.ex:320: Tirexs.HTTP.ok!(:error)
       test/elastic_sync/repo_test.exs:70: (test)



  7) test remove_indicies/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:33
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



  8) test replace_alias/2 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:27
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



  9) test create/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:21
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



 10) test get_alias/1 (ElasticSync.IndexTest)
     test/elastic_sync/index_test.exs:14
     ** (MatchError) no match of right hand side value: :error
     stacktrace:
       test/elastic_sync/index_test.exs:10: ElasticSync.IndexTest.__ex_unit_setup_0/1
       test/elastic_sync/index_test.exs:1: ElasticSync.IndexTest.__ex_unit__/2



Finished in 4.3 seconds
29 tests, 10 failures

Randomized with seed 915898
```

For whatever reason, I seem to have an issue with `delete/1` returning `:error` without any description.

docker compose was suppose to standardize our dev environments but there's gotta be some configuration on my machine that's messing me up.

FWIW:

MacBook Pro - macOS Sierra

Docker community edition for Mac:
Version 17.05.0-ce-rc1-mac8 (16582)
Channel: edge
73d01bb48e

docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Comment by tylerl0706** [comment]
Thanks for all this help - sorry I'm pestering you about my issues. If you want to close this and chat about it somewhere else since it's not an issue with the project technically, I'm totally fine with that.

**Comment by tylerl0706** [comment]
Thoughts:

I'm guessing test failure 1 is happening because deleting the index is failing - at least it's a thought.

The bottom 4 are all failing in the setup which I thought was interesting.

**Comment by rzane** [comment]
Okay, I've reproduced it!

**Comment by tylerl0706** [comment]
Due to Elastic Search 5.3.0 change causing tirexs to fail. Switched project to 5.2.2 for now.
